### ISSUE TITLE
Instalação do helloworld

### ISSUE THREAD

**Issue by praiasoft** [praia/appmenu#13]
Descrição da instalação do projeto inicial, no wiki.

**Comment by alexandre-mbm** [comment]
Este projeto _appmenu_ e o mini-projeto _helloworld_ (issue #4) **são dois**. Acho que as questões relativas ao nosso _helloworld_ devem ficar no repositório dele, ainda não criado. Um repositório de estudo...

**Comment by praiasoft** [comment]
Instalar IDE STS.
Instalação do banco de dados, criação do banco de dados com o nome "teste".
Colocar a senha do banco na aplicação dentro do arquivo "application.properties"
Rodar a aplicação e abrir o PgAdmim para adicionar o usuário para acessar o sistema.

**Comment by alexandre-mbm** [comment]
Continua em praia/helloworld#1
