### ISSUE TITLE
Melhoramento da tela de Login

### ISSUE THREAD

**Issue by praiasoft** [praia/appmenu#15]
Colocar Estilo e layout no html

**Comment by alexandre-mbm** [comment]
Isso é o projeto appmenu? Não é o projeto helloworld?

Você quer fazer o appmenu na doida, sem levantamento de requisitos?! Estou fora.

**Comment by alexandre-mbm** [comment]
Estou migrando para o repositório helloworld recém criado. Por favor não crie mais issues "helloworld" neste repositório appmenu.

**Comment by alexandre-mbm** [comment]
Continua em praia/helloworld#2
